# descriptions.py

ANIMAL_DESCRIPTIONS = {
    'normal': "PANDANGAN MANUSIA (Trichromat)\nMelihat spektrum penuh warna Merah, Hijau, dan Biru secara seimbang dengan detail tajam.",
    'dog': "PANDANGAN ANJING (Dichromat)\nHanya sensitif terhadap warna biru dan kuning. Warna merah atau hijau akan terlihat abu-abu atau kecokelatan.",
    'cat': "PANDANGAN KUCING\nWarna terlihat jauh lebih pudar (desaturasi). Bagian tepi pandangan sangat kabur karena fokus utama berpusat di tengah.",
    'bee': "PANDANGAN LEBAH (Mata Majemuk)\nMata lebah terdiri dari ribuan lensa (pikselasi) dan bergeser ke spektrum warna Ultraviolet (UV) untuk mencari nektar.",
    'snake': "PANDANGAN ULAR (Inframerah/Termal)\nMemiliki organ khusus (pit organ) yang mampu mendeteksi radiasi panas tubuh dari makhluk hidup di sekitarnya.",
    'shark': "PANDANGAN HIU (Monochrome)\nHiu mengalami buta warna total. Penglihatan berbasis hitam-putih dengan kontras sangat tinggi untuk menembus air keruh.",
    'cuttlefish': "PANDANGAN SOTONG (Polarisasi)\nButa warna total, namun mampu mendeteksi arah getaran cahaya (polarisasi) untuk melihat mangsa yang berkamuflase.",
    'eagle': "PANDANGAN ELANG (Super Zoom & Telefoto)\nMemiliki ketajaman visual luar biasa dengan efek perbesaran (zoom) konstan di bagian tengah untuk mengunci target mangsa.",
    'owl': "PANDANGAN BURUNG HANTU (Night Vision)\nSangat sensitif terhadap cahaya rendah. Di siang hari, pandangan mereka terlihat sangat terang benderang (overexposed).",
    'frog': "PANDANGAN KATAK (Detektor Gerakan)\nSangat peka terhadap objek yang bergerak. Objek yang diam (statis) cenderung terlihat buram, gelap, atau diabaikan.",
    'horse': "PANDANGAN KUDA (Blind Spot Tengah)\nKuda memiliki mata di samping kepala, menciptakan pandangan panoramic luas, namun menyisakan titik buta tepat di depan hidung mereka.",
    'pigeon': "PANDANGAN BURUNG MERPATI (Super Color)\nBurung memiliki sistem pentachromat (5 reseptor warna). Mereka melihat gradasi warna, tekstur, dan detail yang tidak bisa dilihat manusia.",
    'bat': "PANDANGAN KELELAWAR (Ekolokasi/Sonar)\nMenggunakan pantulan suara untuk mendeteksi lingkungan. Hasil pencitraannya berbasis tepi objek (edge detection) layaknya radar.",
    'rat': "PANDANGAN TIKUS (Kabur & Lambat)\nTikus memiliki penglihatan yang sangat kabur (rabun dekat) dan gerakan di sekitar mereka terlihat patah-patah atau melambat.",
    'chameleon': "PANDANGAN BUNGLON (Mata Ganda/Split)\nMata bunglon bisa bergerak independen. Disimulasikan dengan membagi layar menjadi dua pandangan kiri dan kanan yang berbeda arah.",
    'shrimp': "PANDANGAN UDANG MANTIS (Mata Tercanggih)\nMemiliki 16 reseptor warna (manusia hanya 3). Mereka melihat dunia penuh dengan distorsi warna ekstrem yang sangat psikedelik.",
    'deer': "PANDANGAN RUSA (Dichromat Merah-Hijau)\nSerupa dengan anjing, rusa tidak bisa membedakan warna merah dan orange. Pakaian berburu warna orange terang justru terlihat abu-abu bagi mereka.",
    'rabbit': "PANDANGAN KELINCI (Panoramic & Grainy)\nMemiliki sudut pandang hampir 360 derajat untuk mendeteksi predator, namun memiliki titik buta tepat di depan mulutnya dan resolusi gambarnya berbintik.",
    'squid': "PANDANGAN CUMI-CUMI (Low Light Monochrome)\nMampu mendeteksi intensitas cahaya sekecil apa pun di laut dalam. Hanya melihat gradasi hitam-putih abu-abu dengan fokus tajam.",
    'crocodile': "PANDANGAN BUAYA (Underwater Scope)\nMemiliki membran pelindung transparan saat masuk ke dalam air, menghasilkan pandangan agak kehijauan/kebiruan dengan visibilitas air yang konstan.",
    'butterfly': "PANDANGAN KUPU-KUPU (Ultraviolet Gairah)\nMelihat warna merah, hijau, biru, dan UV jauh lebih tajam dari lebah guna mendeteksi pola nektar tersembunyi pada kelopak bunga.",
    'penguin': "PANDANGAN PENGUIN (Aquatic Contrast)\nMata penguin beradaptasi kuat untuk melihat warna biru-hijau di dalam air laut guna melacak kawanan ikan meskipun di bawah lapisan es.",
    'cow': "PANDANGAN SAPI (Red-Panoramic)\nSapi tidak bisa melihat warna merah. Pandangan mereka dominan kemerahan-oranye pudar dengan sudut pandang lebar.",
    'goat': "PANDANGAN KAMBING (Pupil Horizontal)\nPupil horizontal memberikan pandangan panorama samping yang sangat luas untuk memantau ancaman predator saat mereka menunduk makan rumput.",
    'goldfish': "PANDANGAN IKAN MAS (Inframerah-UV Combo)\nIkan mas adalah satu-satunya makhluk hidup yang bisa melihat spektrum sinar Inframerah dan Ultraviolet sekaligus. Sangat ramai warna!",
    'spider': "PANDANGAN LABA-LABA (Multi-Lens Blur)\nLaba-laba umumnya memiliki banyak mata namun penglihatan utamanya justru buruk, menciptakan bayangan objek bertumpuk yang buram.",
    'reindeer': "PANDANGAN RUSA KUTUB (Glaring UV)\nMelihat spektrum UV di atas salju. Latar belakang putih bersinar terang, sementara bulu predator/predator gelap akan terlihat sangat kontras.",
    'mosquito': "PANDANGAN NYAMUK (CO2 & Thermal Radar)\nPantauan berbasis sensor panas redup dan sangat buram. Fokus mendeteksi radiasi gas buang napas dan panas kulit mamalia.",
    'archerfish': "PANDANGAN IKAN SUMPIT (Refraction Lens)\nFokus tengah sangat tajam dan terkoreksi dari pembiasan air, sementara sekelilingnya bergelombang seperti permukaan air.",
    'dragonfly': "PANDANGAN CAPUNG (Slow-Mo Ultra HD)\nMemproses visual super cepat sehingga gerakan terlihat patah-patah lambat (slow-mo) dengan sudut pandang cembung ekstrem.",
    'dragonfish': "PANDANGAN IKAN NAGA LAUT (Red Laser Scope)\nLaut dalam yang gelap gulita, namun memiliki senter sorot merah biologis di tengah mata untuk mengunci target diam-diam.",
    'squirrel': "PANDANGAN TUPAI (Pale Dichromat)\nButa warna merah-hijau yang membuat dedaunan terlihat pucat kekuningan, membantu mereka fokus mencari kacang di tanah.",
    'chicken': "PANDANGAN AYAM (Dawn/Twilight Booster)\nMemiliki sensitivitas warna luar biasa di siang hari, namun buta ayam (sangat gelap) begitu cahaya meredup sedikit saja.",
    'elephant': "PANDANGAN GAJAH (Low Resolution Panoramic)\nUkuran mata gajah relatif kecil dibanding tubuhnya. Penglihatan mereka agak kabur untuk jarak jauh namun peka pada gerakan di batas horizontal.",
    'lion': "PANDANGAN SINGA (Predator Twilight)\nSangat tajam saat fajar dan magrib. Memiliki lapisan pemantul cahaya (tapetum lucidum) yang membuat visual malam hari terlihat terang kebiruan.",
    'mole': "PANDANGAN TIKUS TANDAN/MOLE (Light Detector Only)\nHidup di bawah tanah membuat matanya mengecil. Hanya bisa membedakan antara ada cahaya (terang putih) dan gelap (hitam total).",
    'jellyfish': "PANDANGAN UBUR-UBUR (Rhopalium Shadow)\nTidak memiliki otak maupun mata sejati, melainkan sensor bintik cahaya. Hanya bisa melihat bayangan kabur hitam-putih tanpa bentuk.",
    'snail': "PANDANGAN SIPUT (Blurry Vignette)\nMata siput berada di ujung tentakelnya. Tidak bisa fokus dan tidak melihat warna, hanya bayangan buram melingkar di sekeliling arah gerak.",
    'dolphin': "PANDANGAN LUMBA-LUMBA (Sonar Overlay)\nVisual monokromatik bawah air yang bersih, digabungkan dengan garis-garis riak gelombang suara ekolokasi aktif.",
    'vulture': "PANDANGAN BURUNG BANGKAI (Thermal Air Current)\nMelihat kontras daratan yang tajam untuk mendeteksi bangkai dan mendeteksi arus udara panas di langit untuk terbang tanpa mengepakkan sayap.",
    'octopus': "PANDANGAN GURITA (Polarized Contrast)\nTidak melihat warna (colorblind) tetapi mengenali polarisasi cahaya secara presisi untuk membedakan transparansi tubuh mangsa air.",
    'sheep': "PANDANGAN DOMBA (Wide-Angle Guard)\nSudut pandang melebar horizontal 320 derajat dengan titik fokus yang sangat datar di bagian tengah untuk mendeteksi serigala dari kejauhan.",
    'lemur': "PANDANGAN LEMUR (Nocturnal Amber)\nPrimata malam dengan mata besar yang menyerap spektrum cahaya jingga-amber untuk melacak buah dan serangga di kegelapan pohon.",
    'gecko': "PANDANGAN TOKEK (Super Night Color)\nTokek 350 kali lebih peka warna di malam hari daripada manusia. Dunia malam mereka terlihat sangat penuh warna-warni cerah.",
    'scorpio': "PANDANGAN KALA JENGKING (Cyan UV Fluorescence)\nMemiliki mata lateral yang mendeteksi cahaya bintang/bulan. Seluruh tubuh mereka dan lingkungan memancarkan warna cyan pendar.",
    'badger': "PANDANGAN LUWAK (Grayscale Underground)\nPenglihatan monokromatik jarak pendek yang sangat kontras di ruang gelap gulita untuk menggali tanah.",
    'seal': "PANDANGAN ANJING LAUT (Green Deep Sea Scope)\nMata besar yang sangat peka terhadap warna hijau air laut dalam, mengabaikan warna merah sepenuhnya.",
    'firefly': "PANDANGAN KUNANG-KUNANG (Blinking Bioluminescence)\nPandangan malam bintik-bintik kuning-hijau menyala yang berkedip sesuai dengan sinyal komunikasi antar pasangan.",
    'sloth': "PANDANGAN KANGKANG/SLOTH (Static Colorblind)\nMengalami buta warna total sejak lahir dan visualnya sangat lambat serta kabur. Objek bergerak cepat akan terlihat berbayang.",
    'human_night': "BONUS: NIGHT VISION MANUSIA\nSimulasi filter kamera infra merah malam hari buatan manusia (Hijau Monokromatik ala militer)."
}